# Generated by Django 3.1 on 2023-03-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_booth', models.CharField(default=None, max_length=100, null=True)),
                ('Price_NA', models.BigIntegerField(default=None, null=True)),
                ('Price_PA', models.BigIntegerField(default=None, null=True)),
                ('Duration', models.BigIntegerField(default=None, null=True)),
                ('Status', models.CharField(default=None, max_length=20, null=True)),
                ('Date_1', models.DateField(default=None)),
                ('countdown', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'Booths',
            },
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stime', models.CharField(default=None, max_length=100, null=True)),
                ('ETime', models.CharField(default=None, max_length=200, null=True)),
                ('P1Stime', models.CharField(default=None, max_length=200, null=True)),
                ('P1Etime', models.CharField(default=None, max_length=200, null=True)),
                ('P2Stime', models.CharField(default=None, max_length=20, null=True)),
                ('P2Etime', models.EmailField(default=None, max_length=100, null=True)),
                ('Date_0', models.DateField(default=None)),
            ],
            options={
                'db_table': 'Timings',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cars_done', models.CharField(default=None, max_length=100, null=True)),
                ('Cars_remaining', models.BigIntegerField(default=None, null=True)),
                ('Amount_collected', models.BigIntegerField(default=None, null=True)),
                ('Total_time_taken', models.DateTimeField(default=None, max_length=100, null=True)),
                ('Date', models.DateField(default=None)),
                ('Total_time_min', models.BigIntegerField(default=None, null=True)),
                ('Bid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP_CAR_WASH_CENTER.booths')),
            ],
            options={
                'db_table': 'Simulation',
            },
        ),
    ]
