# Generated by Django 3.1 on 2023-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_CAR_WASH_CENTER', '0003_auto_20230323_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='ETime',
            field=models.TimeField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='P1Etime',
            field=models.TimeField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='P1Stime',
            field=models.TimeField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='P2Etime',
            field=models.TimeField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timings',
            name='P2Stime',
            field=models.TimeField(default=None, max_length=20, null=True),
        ),
    ]
