# Generated by Django 3.1 on 2023-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_CAR_WASH_CENTER', '0004_auto_20230323_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='booths',
            name='Max_Cars',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
